<?xml version='1.0'?>
<package format='3'>
  <name>hpp_bezier_com_traj</name>
  <version>8.0.0</version>
  <description>Multi contact trajectory generation for the COM using Bezier curves</description>
  <author>Pierre Fernbach</author>
  <author>Steve Tonneau</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>BSD-2-Clause</license>

  <depend>eigenpy</depend>
  <depend>glpk</depend>
  <depend>hpp_centroidal_dynamics</depend>
  <depend>ndcurves</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
